version: '3'
services:
  database:
    image: postgres:13.1
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: